In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
#Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)

In [3]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [9]:
X = dataset.iloc[:, :-1] .values
y = dataset.iloc[:, 4]. values

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform (X_train)
X_test = scaler.transform(X_test)

In [12]:
from sklearn. neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [13]:
y_pred = classifier.predict (X_test)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix
print (classification_report (y_test, y_pred))
print (confusion_matrix(y_test, y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       0.83      1.00      0.91        10
 Iris-virginica       1.00      0.83      0.91        12

       accuracy                           0.93        30
      macro avg       0.94      0.94      0.94        30
   weighted avg       0.94      0.93      0.93        30

[[ 8  0  0]
 [ 0 10  0]
 [ 0  2 10]]


In [15]:
import pandas as pd
import numpy as np
from fuzzywuzzy import process, fuzz
df1 = pd.read_csv('/Users/denistkachenko/Documents/pages.csv')
df2 = pd.read_csv('/Users/denistkachenko/Documents/pages.csv')
df1['name_from_df2'] = df1['context_user_agent'].apply(lambda x: process.extractOne(x, df2['context_user_agent'].to_list(), score_cutoff=80))
df1[['context_user_agent','name_from_df2']]
df1

KeyboardInterrupt: 