# Numpy
## [data playgroudnd kaggle.com](https://www.kaggle.com/)

In [10]:
import numpy as np

a = np.array([1, 2, 3], dtype='float')
print(a)

[1. 2. 3.]


In [17]:
a= np.array([[1, 2, 3], [4, 5, 6]],  dtype='float')
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
b = a.flatten()
print (b)


[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [20]:
print(a.shape)

(2, 3)


In [21]:
c= a.reshape(3,2)
print(c)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [22]:
d= a.reshape(6,1)
print(d)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]]


In [23]:
d = np.arange(0, 10, 2)
print(d)

[0 2 4 6 8]


In [9]:
d = np.linspace(0, 10, 7)
print(d)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]


In [30]:
d = np.random.rand(2,4)
print(d)

[[0.43794591 0.37639735 0.34247304 0.73990409]
 [0.14158983 0.46201537 0.71814829 0.381648  ]]


In [26]:
d.shape

(3, 2, 4, 19)

In [31]:
c = d.tobytes()
print (c)

b'FXIEN\x07\xdc?\xb6*"\xea\xe4\x16\xd8?\xfc\xed\x90\x05\x14\xeb\xd5?\x9fH\x81VK\xad\xe7?\xe0\x11\xd6\x97\x9d\x1f\xc2?\xaa\xd7(\xed\xa8\x91\xdd?\xc2\xb9\xcd\x1f\x12\xfb\xe6?`B+\xb9\xebl\xd8?'


In [32]:
d = np.frombuffer(c)
print(d)

[0.43794591 0.37639735 0.34247304 0.73990409 0.14158983 0.46201537
 0.71814829 0.381648  ]


In [40]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
c= np.concatenate((a,b))
d = np.concatenate((a,b), axis=1)

print(d)

[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [20]:
print(b)

print(a+b)
print (c)
print (d)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [18]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
a = np.array([1.19, 1.51, 1.99], float)
b=np.floor(a)

c = np.ceil(a)
d = np.rint(a)
e = np.around(a)
print (a)
print (b)
print (c)
print (d)
print (e)

[1.19 1.51 1.99]
[1. 1. 1.]
[2. 2. 2.]
[1. 2. 2.]
[1. 2. 2.]


In [51]:
a = np.array([3, 4, 3], float)
b = a.sum()
c = a.prod()
d = a.mean()
e = a.sort()
print (e)

None


# Pandas

In [53]:
import pandas as pd


series = pd.Series([1, 2, 3, 4, 5])
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [55]:
time = pd.date_range('1/1/2025', periods=6, freq='m')

/var/folders/1w/5fknmcjj7_g7sfbf2lffwy1h0000gn/T/ipykernel_44798/3641614152.py:1: FutureWarning: 'm' is deprecated and will be removed in a future version, please use 'ME' instead.
  time = pd.date_range('1/1/2025', periods=6, freq='m')


DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30'],
              dtype='datetime64[ns]', freq='ME')

In [56]:
time

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30'],
              dtype='datetime64[ns]', freq='ME')

In [57]:
series = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [58]:
series = pd.Series({'a':1, 'b':2, 'c':3, 'd':4, 'e':5})
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [61]:
sort = series.sort_values(ascending=False)
print(sort)

e    5
d    4
c    3
b    2
a    1
dtype: int64


In [69]:
print(series['a'])

1


In [63]:
print(series[0])

1


/var/folders/1w/5fknmcjj7_g7sfbf2lffwy1h0000gn/T/ipykernel_44798/2983294328.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series[0])


In [64]:
print(series[0:3])

a    1
b    2
c    3
dtype: int64


In [65]:
sort2 = series.sort_index(ascending=False)
print(sort2)

e    5
d    4
c    3
b    2
a    1
dtype: int64


In [66]:
print(series[series > 2])

c    3
d    4
e    5
dtype: int64


In [67]:
print(series * 2)

a     2
b     4
c     6
d     8
e    10
dtype: int64


# Dataframes

In [70]:
data = {'Country': ['Belgium', 'India', 'Brazil'],
'Capital': ['Brussels', 'New Delhi', 'Brasília'],
'Population': [11190846, 1303171035, 207847528]}
df = pd.DataFrame(data,columns=['Country', 'Capital', 'Population'])
df


Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasília   207847528

In [71]:
df = pd.DataFrame(data,columns=['Country', 'Capital', 'Population'], index=['a', 'b', 'c'])
print(df)

   Country    Capital  Population
a  Belgium   Brussels    11190846
b    India  New Delhi  1303171035
c   Brazil   Brasília   207847528


In [80]:
df = pd.read_csv('/Users/denistkachenko/Downloads/products.csv', sep=',', on_bad_lines='skip', encoding='utf-8', lineterminator='\n', dtype=str, low_memory=False, na_values=['NA', 'NaN', ''], keep_default_na=True)

df.head()

id                            product_name  \
0  1                           McLaren 675LT   
1  2                Rolls-Royce Wraith Coupe   
2  3  2016 Lamborghini Aventador Convertible   
3  4                             BMW Sport 4   
4  5                   Aston Martin Series 5   

                           product_summary  \
0  Inspired by the McLaren F1 GTR Longtail   
1                                      NaN   
2                                      NaN   
3                BMW Sport special edition   
4      Aston Martin Series special edition   

                                 product_description   price discount  
0  Performance is like strikin and the seven-spee...  349500   1000.0  
1  Inspired by the words of Sir Henry Royce, this...  304000      NaN  
2  Based on V12, this superveloce has been develo...  271000    500.0  
3  BMW Sport 4 is designed for performance and lu...  209324    726.0  
4  Aston Martin Series 5 is designed for performa...  114301   8342.0

In [63]:

df['product_summary'].dropna(inplace=True)


In [81]:
df.date = pd.to_datetime(df.date)
print(df.info())

AttributeError: 'DataFrame' object has no attribute 'date'

In [82]:
df.fillna(0, inplace=True)
df.dropna(inplace=True)




In [32]:


df.date= pd.to_datetime(df.date).dt.to_period('M')
df['month'] = df.date.dt.month

In [33]:
df['month'] = df.date.dt.month


In [42]:
df = df.rename(columns={'date':'year'})
df = df.rename(columns={'month':'date'})

In [41]:
df.head()

year  revenue  month
0  2020-02     3.98      2
1  2020-03    18.86      3
2  2020-04    27.49      4
3  2020-05   512.26      5
4  2020-06  1403.98      6